<?php

/**
 * Implements hook_preprocess_status_message().
 *
 * Remove Drupal commerce default messages.
 */
function mj_commerce_paysafe_preprocess_status_messages(&$variables) {

  // Ensure that we have error messages to process.
  if (isset($variables['message_list']['error']) && count($variables['message_list']['error']) > 0) {

    // Step through each of the error messages and remove Drupal commerce
    // default mesasges.
    foreach ($variables['message_list']['error'] as $key => $m) {

      // If it is a default Drupal commerce error message, remove it.
      if (
        $m == 'We encountered an error processing your payment method. Please verify your details and try again.' ||
        $m == 'We encountered an unexpected error processing your payment method. Please try again later.'
      ) {
        unset($variables['message_list']['error'][$key]);
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * Remove option to add new address.
 */
function mj_commerce_paysafe_form_commerce_checkout_flow_multistep_default_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  // Unset adding a new address, users will have to edit their current address.
  // Just makes things easier.
  unset($form['payment_information']['add_payment_method']['billing_information']['select_address']['#options']['_new']);
}
