# config/schema/mj_commerce_paysafe.schema.yml
mj_commerce_paysafe.commerce_payment_gateway.plugin.paysafe_offsite_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    endpoint:
      type: string
      label: 'Endpoint'
    account_id:
      type: string
      label: 'Account ID'
    username:
      type: string
      label: 'Username'
    api_key:
      type: string
      label: 'API key'
